---
dist: bionic
sudo: required
language: python

env:
  - SCENARIO=default MOLECULE_IMAGE=centos/7
  - SCENARIO=teardown MOLECULE_IMAGE=centos/7
  - SCENARIO=tang MOLECULE_IMAGE=centos/7
  - SCENARIO=default MOLECULE_IMAGE=centos/8
  - SCENARIO=teardown MOLECULE_IMAGE=centos/8
  # FIXME: tang scenario fails on CentOS 8 with 'Could not find the requested
  # service clevis-luks-askpass.path: host'
  # - SCENARIO=tang MOLECULE_IMAGE=centos/8
  # Official ubuntu/focal64 image does not support the libvirt provider.
  - SCENARIO=default MOLECULE_IMAGE=generic/ubuntu2004
  - SCENARIO=teardown MOLECULE_IMAGE=generic/ubuntu2004
  - SCENARIO=tang MOLECULE_IMAGE=generic/ubuntu2004

install:
  # Install libvrt & KVM
  - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev

    # Download Vagrant & Install Vagrant package
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
  - sudo dpkg -i vagrant_2.2.14_x86_64.deb

  # Vagrant correctly installed?
  - vagrant --version

  # Install vagrant-libvirt Vagrant plugin
  - sudo vagrant plugin install vagrant-libvirt

  - pip install tox

script:
  - export VENV=$(dirname $(which python))
  - tox -e py3
  - sudo bash -c ". $VENV/activate && MOLECULE_IMAGE=$MOLECULE_IMAGE tox -e molecule -- -s $SCENARIO"

after_failure:
  - echo "vagrant error log:"
  - sudo cat /root/.cache/molecule/ansible-role-luks/default/vagrant-luks-molecule.err || true

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
