---
dist: bionic
sudo: required
language: python

install:
  # Install libvrt & KVM
  - sudo apt-get update && sudo apt-get install -y bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev

  # Download Vagrant & Install Vagrant package
  - sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
  - sudo dpkg -i vagrant_2.2.7_x86_64.deb

  # Vagrant correctly installed?
  - vagrant --version

  # Install vagrant-libvirt Vagrant plugin
  - sudo vagrant plugin install vagrant-libvirt

  - pip install 'molecule<3.0.0' ansible===2.9.6 python-vagrant

script:
  - molecule lint
  - sudo -E molecule test

after_failure:
  - echo "vagrant error log:"
  - cat /home/travis/.cache/molecule/ansible-role-luks/default/vagrant-centos-7-molecule.err || true

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
