---

- name: Create the luks device
  luks_device:
    device: "{{ item.device }}"
    state: "present"
    keyfile: "{{ item | luks_keypath }}"
  with_items: "{{ luks_devices }}"
  tags: skip_when_testing_docker
  become: true
