---
- name: Install dependencies
  vars:
    # List of groups of packages that may be conditionally installed.
    package_groups:
      - packages:
          - cryptsetup
        required: true
      - packages:
          # For /usr/lib/systemd/system-generators/systemd-cryptsetup-generator. In
          # RedHat 7, the was included in the systemd package.
          - systemd-udev
        required: "{{ ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version == '8' }}"
      - packages:
          - clevis-systemd
          - clevis-luks
          - scrub
        required: "{{ luks_devices | selectattr('mode', 'defined') | selectattr('mode', 'in', ['tang', 'tpm2']) | list | length > 0 }}"
      - packages:
          - clevis-dracut
          - nmap-ncat
        required: "{{ luks_devices | selectattr('mode', 'defined') | selectattr('mode', 'equalto', 'tpm2') | list | length > 0 }}"
  package:
    name: "{{ package_groups | selectattr('required') | map(attribute='packages') | flatten | list }}"
    state: present
  become: true
