---
- name: Install dependencies
  package:
    name:
      - cryptsetup
      # for /usr/lib/systemd/system-generators/systemd-cryptsetup-generator
      - systemd-udev
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Install clevis
  package:
    name:
      - clevis-systemd
      - clevis-luks
      - scrub
    state: present
  become: true
  when: ansible_os_family == "RedHat" and luks_devices | selectattr('mode', 'tang')
