---

- name: Check if luks enabled on device
  command: cryptsetup isLuks "{{ item.device }}"
  changed_when: false
  register: isluks
  failed_when: false
  become: true

- name: Ensure parent directory exists
  file:
    state: directory
    path: "{{ keysetup_directory }}"
    mode: 0770
    owner: root
    group: root
  become: true
  when: isluks.rc != 0

- name: Generate a random key file
  # Old verisons of clevis have issues with long keys
  shell: |-
    set -o pipefail
    head /dev/random | tr -dc 'A-Za-z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' | head -c 16 > {{ keysetup_directory }}/{{ keysetup_keyname }}
  args:
    creates: "{{ keysetup_directory }}/{{ keysetup_keyname }}"
  become: true
  when:
    - keysetup_action == "generate"
    - isluks.rc != 0

- name: Copy pre-generated file
  copy:
    src: "{{ keysetup_src }}"
    dest: "{{ keysetup_directory }}/{{ keysetup_keyname }}"
  become: true
  when:
    - keysetup_action == "copy"
    - isluks.rc != 0

- name: Set permissions of keyfile
  file:
    path: "{{ keysetup_directory }}/{{ keysetup_keyname }}"
    state: file
    mode: "0660"
    owner: root
    group: root
  become: true
  when: isluks.rc != 0
