---
- name: Validate luks_devices
  assert:
    that:
      - "'device' in item"
      # must be absolute path
      - "item.device.startswith('/')"
  with_items: "{{ luks_devices }}"

- name: Validate tang configuration
  assert:
    that:
      - "'tang_server' in item"
      - "'tang_adv' in item"
  when: item.mode | default('keyfile') == "tang"
  with_items: "{{ luks_devices }}"
