---
- name: Display diagnostic informaton (variables)
  debug:
    msg: "{{ item }}: {{ hostvars[inventory_hostname][item] }}"
  with_items:
    - ansible_distribution
    - ansible_distribution_version

- name: Display diagnostic informaton (environment)
  debug:
    msg: "{{ item }}: {{ lookup('env', item) | default('UNSET', true) }}"
  with_items:
    - MOLECULE_IMAGE
    - SCENARIO
