---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: luks-molecule
    box: ${MOLECULE_IMAGE:-centos/7}
    cpus: 1
    memory: 1024
    provider_raw_config_args:
      - "random :model => 'random'"
provisioner:
  name: ansible
  options:
    become: true
  lint:
    name: ansible-lint
    options:
      R: true
scenario:
  name: teardown
  # Remove idempotenace as we are tearing down
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  directory: tests
  options:
    verbose: true
    sudo: true
  lint:
    name: flake8
