---
- name: Prepare
  hosts: localhost
  gather_facts: false
  vars:
    ansible_become: false
  tasks:
    # It is advisable to check this file into your config repository rather
    # than downloading it dynamically. As this is the host fingerprint and
    # should not change.
    - name: Download adv
      get_url:
        url: http://{{ hostvars[groups["all"][0]]["ansible_host"] }}:1234/adv
        dest: "files/adv"

- name: Converge
  hosts: all
  vars:
    luks_devices:
      - device: /dev/vdb
        name: cryptotest
        mode: tang
        tang_server: 127.0.0.1:1234
        tang_adv: adv
  roles:
    - role: stackhpc.luks
