---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  name: yamllint
platforms:
  - name: luks-molecule
    box: ${MOLECULE_IMAGE:-centos/7}
    cpus: 1
    memory: 1024
    provider_raw_config_args:
      - "random :model => 'random'"
provisioner:
  name: ansible
  options:
    become: true
  lint:
    name: ansible-lint
    options:
      R: true
scenario:
  name: default
verifier:
  name: testinfra
  directory: tests
  options:
    verbose: true
    sudo: true
  lint:
    name: flake8
