---
- name: Converge
  hosts: all
  vars:
    luks_devices:
      - device: /dev/loop0
        name: cryptotest
      - device: /dev/loop1
        name: cryptotest1
    skip_when_testing_docker: true
  roles:
    - role: stackhpc.luks
